-- MySQL Script generated by MySQL Workbench
-- Wed Nov 30 08:13:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema-voo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema-voo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema-voo` DEFAULT CHARACTER SET utf8 ;
USE `sistema-voo` ;

-- -----------------------------------------------------
-- Table `sistema-voo`.`Aviao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-voo`.`Aviao` (
  `id` INT NOT NULL,
  `modelo` VARCHAR(45) NULL,
  UNIQUE INDEX `idAviao_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-voo`.`Assento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-voo`.`Assento` (
  `id` INT NOT NULL,
  `tipo_assento` VARCHAR(45) NULL,
  `id_aviao` INT NOT NULL,
  PRIMARY KEY (`id`, `id_aviao`),
  UNIQUE INDEX `idAssento_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Assento_Aviao_idx` (`id_aviao` ASC) VISIBLE,
  CONSTRAINT `fk_Assento_Aviao`
    FOREIGN KEY (`id_aviao`)
    REFERENCES `sistema-voo`.`Aviao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-voo`.`Passageiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-voo`.`Passageiros` (
  `cpf` VARCHAR(11) NOT NULL,
  `id` INT NOT NULL,
  `identidade` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `telefone` INT NULL,
  `endereço` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `Assento_id` INT NOT NULL,
  `Assento_id_aviao` INT NOT NULL,
  PRIMARY KEY (`cpf`, `id`, `identidade`, `Assento_id`, `Assento_id_aviao`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Passageiros_Assento1_idx` (`Assento_id` ASC, `Assento_id_aviao` ASC) VISIBLE,
  CONSTRAINT `fk_Passageiros_Assento1`
    FOREIGN KEY (`Assento_id` , `Assento_id_aviao`)
    REFERENCES `sistema-voo`.`Assento` (`id` , `id_aviao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-voo`.`Tripulaçao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-voo`.`Tripulaçao` (
  `id` INT NOT NULL,
  `piloto` VARCHAR(45) NULL,
  `comissario` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-voo`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-voo`.`Cidade` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'C';


-- -----------------------------------------------------
-- Table `sistema-voo`.`Aeroporto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-voo`.`Aeroporto` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  `id_cidade` INT NOT NULL,
  PRIMARY KEY (`id`, `id_cidade`),
  UNIQUE INDEX `idAeroporto_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Aeroporto_Cidade1_idx` (`id_cidade` ASC) VISIBLE,
  CONSTRAINT `fk_Aeroporto_Cidade1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `sistema-voo`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema-voo`.`Voo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-voo`.`Voo` (
  `id` INT NOT NULL,
  `id_aviao` INT NOT NULL,
  `id_tripulaçao` INT NOT NULL,
  `id_aeroporto_chegada` INT NOT NULL,
  `id_aeroporto_saida` INT NOT NULL,
  UNIQUE INDEX `idVoo_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `id_aviao`, `id_tripulaçao`, `id_aeroporto_chegada`, `id_aeroporto_saida`),
  INDEX `fk_Voo_Aviao1_idx` (`id_aviao` ASC) VISIBLE,
  INDEX `fk_Voo_Tripulaçao1_idx` (`id_tripulaçao` ASC) VISIBLE,
  INDEX `fk_Voo_Aeroporto1_idx` (`id_aeroporto_chegada` ASC) VISIBLE,
  INDEX `fk_Voo_Aeroporto2_idx` (`id_aeroporto_saida` ASC) VISIBLE,
  CONSTRAINT `fk_Voo_Aviao1`
    FOREIGN KEY (`id_aviao`)
    REFERENCES `sistema-voo`.`Aviao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_Tripulaçao1`
    FOREIGN KEY (`id_tripulaçao`)
    REFERENCES `sistema-voo`.`Tripulaçao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_Aeroporto1`
    FOREIGN KEY (`id_aeroporto_chegada`)
    REFERENCES `sistema-voo`.`Aeroporto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_Aeroporto2`
    FOREIGN KEY (`id_aeroporto_saida`)
    REFERENCES `sistema-voo`.`Aeroporto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
